### ISSUE TITLE
Hello Word

### ISSUE THREAD

**Issue by LoeiFy** [LoeiFy/loeify.github.io#2]
此主题的预览 / This theme's showcase

## Headers

```md
## This is an h2 tag
### This is an h3 tag
###### This is an h6 tag
```

## Emphasis

```md
*This text will be italic*
_This will also be italic_

**This text will be bold**
__This will also be bold__

_You **can** combine them_

~~this~~
```

*This text will be italic*
_This will also be italic_

**This text will be bold**
__This will also be bold__

_You **can** combine them_

~~this~~

## Lists

**Unordered**

```md
* Item 1
* Item 2
  * Item 2a
  * Item 2b
```

* Item 1
* Item 2
  * Item 2a
  * Item 2b

**Ordered**

```md
1. Item 1
1. Item 2
1. Item 3
   1. Item 3a
   1. Item 3b
```

1. Item 1
1. Item 2
1. Item 3
   1. Item 3a
   1. Item 3b

## Images

```md
![GitHub Logo](https://avatars2.githubusercontent.com/u/2193211?s=460&v=4)

[![Deploy Website](https://github.com/LoeiFy/loeify.github.io/actions/workflows/action.yml/badge.svg)](https://github.com/LoeiFy/loeify.github.io/actions/workflows/action.yml)
```

![GitHub Logo](https://avatars2.githubusercontent.com/u/2193211?s=460&v=4)

[![Deploy Website](https://github.com/LoeiFy/loeify.github.io/actions/workflows/action.yml/badge.svg)](https://github.com/LoeiFy/loeify.github.io/actions/workflows/action.yml)

## Links

```md
http://github.com - automatic!
[GitHub](http://github.com)
```

http://github.com - automatic!
[GitHub](http://github.com)

## Blockquotes

```md
As Kanye West said:

> We're living the future so
> the present is our past.
```

As Kanye West said:

> We're living the future so
> the present is our past.

## Inline code

```md
I think you should use an
`<addr>` element here instead.
```

I think you should use an
`<addr>` element here instead.

## Syntax highlighting

```javascript
const a = 1
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```

## Task Lists

```md
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item
```

- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

## Table

```md
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column
```

First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

# Latex Math

```md
inline: $x^2+y^2 = 1$

next line: $$x^2+y^2 = 1$$
```

inline: $x^2+y^2 = 1$

next line: $$x^2+y^2 = 1$$

## 中文

我年幼时就非常爱好读书。（因为）家里贫穷，（所以）没有办法买书来阅读，常常向藏书的人家去借，亲自抄录，计算着日期按时送还。冬天非常寒冷，砚台里的墨汁像冰一样坚硬，手指（冻得）不能弯曲伸直，也不敢懈怠。
